import { useState } from "react";
import { usePortfolio } from "../PortfolioContext";
import { generatePortfolioHTML } from "./HtmlGenerator";
import { Download, Copy, Check, FileCode } from "lucide-react";

export function ExportPanel() {
  const { data } = usePortfolio();
  const [copied, setCopied] = useState(false);
  const [showCode, setShowCode] = useState(false);

  const html = generatePortfolioHTML(data);

  const downloadHTML = () => {
    const name = data.personalInfo.name?.toLowerCase().replace(/\s+/g, "-") || "portfolio";
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${name}-portfolio.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadZip = async () => {
    const name = data.personalInfo.name?.toLowerCase().replace(/\s+/g, "-") || "portfolio";
    const { default: JSZip } = await import("jszip");
    const zip = new JSZip();
    zip.file("index.html", html);
    zip.file("README.md", `# ${data.personalInfo.name || "Portfolio"} Portfolio\n\nGenerated by AI Portfolio Builder - WebCare by ISHConnect`);
    const blob = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${name}-portfolio.zip`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const copyHTML = async () => {
    await navigator.clipboard.writeText(html);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const hasData = data.personalInfo.name || data.skills.length > 0 || data.projects.length > 0;

  if (!hasData) {
    return (
      <div className="h-full flex items-center justify-center text-gray-400 text-sm p-8 text-center">
        <div>
          <p className="text-4xl mb-3">&#128190;</p>
          <p>Add your details first, then export</p>
        </div>
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col p-6">
      <h3 className="font-bold text-gray-900 text-sm mb-2">Export Portfolio</h3>
      <p className="text-xs text-gray-400 mb-6">Download as HTML or ZIP package</p>

      <div className="space-y-3 mb-6">
        <button onClick={downloadHTML} className="w-full flex items-center justify-between px-4 py-3.5 bg-orange-500 hover:bg-orange-600 text-white rounded-xl transition-colors text-sm font-semibold">
          <span className="flex items-center gap-2"><Download className="w-4 h-4" /> Download HTML</span>
          <span className="text-white/70 text-xs">Standalone .html</span>
        </button>

        <button onClick={downloadZip} className="w-full flex items-center justify-between px-4 py-3.5 bg-gray-900 hover:bg-gray-800 text-white rounded-xl transition-colors text-sm font-semibold">
          <span className="flex items-center gap-2"><Download className="w-4 h-4" /> Download ZIP</span>
          <span className="text-white/70 text-xs">Full package</span>
        </button>

        <button onClick={copyHTML} className="w-full flex items-center justify-between px-4 py-3.5 border border-gray-200 hover:border-orange-300 text-gray-700 rounded-xl transition-colors text-sm font-semibold">
          <span className="flex items-center gap-2">{copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />} {copied ? "Copied!" : "Copy HTML"}</span>
          <span className="text-gray-400 text-xs">To clipboard</span>
        </button>

        <button onClick={() => setShowCode(!showCode)} className="w-full flex items-center justify-between px-4 py-3.5 border border-gray-200 hover:border-orange-300 text-gray-700 rounded-xl transition-colors text-sm font-semibold">
          <span className="flex items-center gap-2"><FileCode className="w-4 h-4" /> {showCode ? "Hide Code" : "View HTML Code"}</span>
          <span className="text-gray-400 text-xs">Source</span>
        </button>
      </div>

      {showCode && (
        <div className="flex-1 overflow-auto">
          <pre className="text-[11px] text-gray-700 bg-gray-50 border border-gray-200 rounded-xl p-4 overflow-auto whitespace-pre-wrap max-h-[400px]">{html}</pre>
        </div>
      )}

      <div className="mt-auto pt-4 border-t border-gray-100">
        <div className="flex items-center gap-2 text-xs text-gray-400">
          <div className="w-2 h-2 rounded-full bg-green-400" />
          Generated HTML is {html.length.toLocaleString()} bytes
        </div>
        <p className="text-[10px] text-gray-400 mt-1">Works offline, fully responsive, SEO-optimized</p>
      </div>
    </div>
  );
}
